name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node: 18
        cache: 'npm'
        node-version: 18
    - name: Test
      run: |
        npm ci
        npm run lint
        npm run spellcheck
        # npm run test:ci
        npm run build:prod
      env:
        CI: true
